# Generated by Django 6.0.7 on 2026-08-23 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0003_tickethistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentiment", models.CharField(blank=True, default="", max_length=20)),
                ("summary", models.TextField(blank=True, default="")),
                ("faq_answer", models.TextField(blank=True, default="")),
                ("faq_similarity_score", models.FloatField(blank=True, null=True)),
                (
                    "faq_confidence_level",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "model_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("status", models.CharField(default="COMPLETED", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ai_analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
