# Generated by Django 5.0.9 on 2026-08-24 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0003_tickethistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Row creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last modification time')),
                ('analysis_type', models.CharField(choices=[('CLASSIFICATION', 'Classification'), ('PRIORITY', 'Priority'), ('SENTIMENT', 'Sentiment'), ('SUMMARY', 'Summary')], max_length=30)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=100)),
                ('input_hash', models.CharField(max_length=128)),
                ('result_json', models.JSONField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('LOW_CONFIDENCE', 'Low confidence')], default='SUCCESS', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='tickets.ticket')),
            ],
            options={
                'verbose_name_plural': 'AI analyses',
                'db_table': 'ai_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Row creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last modification time')),
                ('feedback_type', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('CORRECTED', 'Corrected'), ('REJECTED', 'Rejected')], max_length=20)),
                ('original_prediction', models.JSONField()),
                ('corrected_prediction', models.JSONField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True)),
                ('is_retraining_eligible', models.BooleanField(default=False)),
                ('retraining_status', models.CharField(choices=[('PENDING', 'Pending'), ('USED', 'Used'), ('EXCLUDED', 'Excluded')], default='PENDING', max_length=20)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai.aianalysis')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback_reviews', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='tickets.ticket')),
            ],
            options={
                'verbose_name_plural': 'AI feedback',
                'db_table': 'ai_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Row creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last modification time')),
                ('suggestion_type', models.CharField(choices=[('REPLY', 'Reply'), ('FAQ', 'FAQ'), ('ACTION', 'Action')], max_length=20)),
                ('suggested_text', models.TextField()),
                ('source_json', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='ai.aianalysis')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='tickets.ticket')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI suggestions',
                'db_table': 'ai_suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
