# Generated by Django 5.0.9 on 2026-08-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('tickets', '0003_tickethistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['ticket', 'analysis_type', 'created_at'], name='ai_analysis_lookup_idx'),
        ),
    ]
