# Generated by Django 5.0.9 on 2026-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aianalysis_ai_analysis_lookup_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]


