# Generated by Django 5.0.9 on 2026-08-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aianalysis_response_time_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='analysis_type',
            field=models.CharField(choices=[('CLASSIFICATION', 'Classification'), ('PRIORITY', 'Priority'), ('SENTIMENT', 'Sentiment'), ('SUMMARY', 'Summary'), ('FAQ', 'FAQ')], max_length=30),
        ),
    ]
