# Generated by Django 5.0.9 on 2026-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_tickethistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI classification confidence percentage (0-100).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], max_length=20, null=True),
        ),
    ]
