# Generated by Django 5.0.9 on 2026-08-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_ai_confidence_ticket_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='is_internal',
            field=models.BooleanField(blank=True, default=False, help_text='Internal notes are visible to agents, supervisors and admins only. Requesters must never see them.'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status changed'), ('PRIORITY_CHANGED', 'Priority changed'), ('CATEGORY_CHANGED', 'Category changed'), ('INTERNAL_NOTE', 'Internal note'), ('PUBLIC_REPLY', 'Public reply'), ('ATTACHMENT_ADDED', 'Attachment added')], max_length=30),
        ),
    ]
