# Generated by Django 5.0.9 on 2026-08-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticketcomment_is_internal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status changed')], max_length=20),
        ),
    ]
