# Generated by Django 5.0.9 on 2026-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_tickethistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status changed'), ('PRIORITY_CHANGED', 'Priority changed'), ('CATEGORY_CHANGED', 'Category changed'), ('INTERNAL_NOTE', 'Internal note'), ('PUBLIC_REPLY', 'Public reply'), ('ATTACHMENT_ADDED', 'Attachment added')], max_length=30),
        ),
    ]
