# Generated by Django 5.0.9 on 2026-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_tickethistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status changed'), ('PRIORITY_CHANGED', 'Priority changed'), ('CATEGORY_CHANGED', 'Category changed')], max_length=20),
        ),
    ]
