# Generated by Django 5.0.9 on 2026-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_tickethistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created')], max_length=30),
        ),
    ]
