# Generated by Django 5.0.9 on 2026-09-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_tickethistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the ticket first reached a resolved or closed state. Set automatically on save; cleared if the ticket is reopened.', null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status changed'), ('PRIORITY_CHANGED', 'Priority changed'), ('CATEGORY_CHANGED', 'Category changed'), ('PUBLIC_REPLY', 'Public reply'), ('INTERNAL_NOTE', 'Internal note')], max_length=30),
        ),
    ]
