# Generated by hand, following the pattern of
# organization/migrations/0002_seed_departments.py

from django.db import migrations


# (category_code, category_name, department_code)
# department_code must match one of the codes seeded in
# organization/migrations/0002_seed_departments.py
CATEGORIES = [
    ("HARDWARE", "Hardware Issue", "IT_SUPPORT"),
    ("SOFTWARE", "Software Issue", "IT_SUPPORT"),
    ("NETWORK", "Network / Internet", "IT_SUPPORT"),
    ("ACCOUNT_ACCESS", "Account & Access", "IT_SUPPORT"),
    ("BILLING", "Billing / Payment", "FINANCE"),
    ("REFUND", "Refund Request", "FINANCE"),
    ("ADMISSION_INQUIRY", "Admission Inquiry", "ADMISSIONS"),
    ("DOCUMENT_REQUEST", "Document Request", "ADMISSIONS"),
    ("EXAM_SCHEDULE", "Exam Schedule", "EXAMINATION"),
    ("RESULT_ISSUE", "Result Issue", "EXAMINATION"),
    ("GENERAL_QUERY", "General Query", "GENERAL"),
    ("OTHER", "Other", "GENERAL"),
]


def seed_categories(apps, schema_editor):
    TicketCategory = apps.get_model("classification", "TicketCategory")
    Department = apps.get_model("organization", "Department")

    for code, name, dept_code in CATEGORIES:
        department = Department.objects.filter(code=dept_code).first()
        TicketCategory.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "department": department,
                "is_active": True,
            },
        )


def unseed_categories(apps, schema_editor):
    TicketCategory = apps.get_model("classification", "TicketCategory")
    TicketCategory.objects.filter(code__in=[c for c, _, _ in CATEGORIES]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("classification", "0001_initial"),
        ("organization", "0002_seed_departments"),
    ]
    operations = [migrations.RunPython(seed_categories, unseed_categories)]
    