# Generated by Django 5.0.9 on 2026-08-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Row creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last modification time')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgearticle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_article_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_article_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgearticleversion',
            constraint=models.UniqueConstraint(fields=('article', 'version_number'), name='uniq_article_version'),
        ),
    ]
