# Generated by Django 5.0.9 on 2026-08-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgearticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='include_in_ai_knowledge_base',
            field=models.BooleanField(default=False),
        ),
    ]
