# Generated by Django 5.0.9 on 2026-09-03 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledgearticle_include_in_ai_knowledge_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticleFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Row creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last modification time')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_faqs', to='knowledge.knowledgearticle')),
            ],
            options={
                'db_table': 'knowledge_article_faqs',
                'ordering': ['-created_at'],
            },
        ),
    ]
