# Generated by Django 5.0.9 on 2026-08-10 12:55

from django.db import migrations





DEPARTMENTS = [
    ("IT_SUPPORT", "IT Support"),
    ("FINANCE", "Finance"),
    ("ADMISSIONS", "Admissions"),
    ("EXAMINATION", "Examination"),
    ("GENERAL", "General"),
]


def seed_departments(apps, schema_editor):
    Department = apps.get_model("organization", "Department")
    for code, name in DEPARTMENTS:
        Department.objects.update_or_create(
            code=code, defaults={"name": name, "is_active": True},
        )


def unseed_departments(apps, schema_editor):
    Department = apps.get_model("organization", "Department")
    Department.objects.filter(code__in=[c for c, _ in DEPARTMENTS]).delete()


class Migration(migrations.Migration):
    dependencies = [("organization", "0001_initial")]
    operations = [migrations.RunPython(seed_departments, unseed_departments)]
    
