# Generated by Django 5.0.9 on 2026-08-10 07:50
#
# This file was produced by `manage.py makemigrations accounts` — it is the
# schema half of Phase 2 (the CREATE TABLE statements for users, roles,
# permissions, user_roles and role_permissions).
#
# Do not hand-edit generated migrations. Change accounts/models.py and run
# `makemigrations` again; Django writes the follow-up migration for you.

# Generated by Django 5.0.9 on 2026-08-10 07:50
#
# This file was produced by `manage.py makemigrations accounts` — it is the
# schema half of Phase 2 (the CREATE TABLE statements for users, roles,
# permissions, user_roles and role_permissions).
#
# Do not hand-edit generated migrations. Change accounts/models.py and run
# `makemigrations` again; Django writes the follow-up migration for you.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Row creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last modification time')),
                ('username', models.CharField(help_text='Unique login identifier', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='Stored lowercase', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Unchecked instead of deleting a user, so their history survives')),
                ('is_staff', models.BooleanField(default=False, help_text='Allows access to Django Admin at /admin/')),
                ('is_superuser', models.BooleanField(default=False, help_text='Bypasses every permission check')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'View all tickets'", max_length=150)),
                ('code', models.CharField(help_text="Checked in code, e.g. 'ticket.view_all'", max_length=100, unique=True)),
                ('module', models.CharField(help_text="Feature area this permission belongs to, e.g. 'ticket'", max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Row creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last modification time')),
                ('name', models.CharField(help_text="Display name, e.g. 'Agent'", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Machine-readable code the application checks, e.g. 'AGENT'", max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles are seeded by a migration and must not be deleted')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who granted the role; NULL when granted by the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='accounts.UserRole', to='accounts.role'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uniq_user_role'),
        ),
    ]
