# Generated by Django 5.0.9 on 2026-08-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set automatically the first time this user logs in successfully. Not the same as is_active — a user can be active but never verified.'),
        ),
    ]
