# Generated by Django 5.0.9 on 2026-08-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_verified'),
        ('organization', '0002_seed_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.department'),
        ),
    ]
