# Generated by Django 5.0.9 on 2026-08-26 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_ai_review_permission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrole',
            name='uniq_user_role',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
